train:
  seed: 42
  epochs: 10
  batch_size: 32
  accumulate_grad_batches: 1
  gradient_clip_val: 0.0
  gradient_checkpointing: false
  validation_interval: 0.2
  log_every_n_steps: 10
  
data:
  train_img_size: 224
  val_img_size: 224
  batch_size: 32
  num_workers: 15

model:
  name: "timm_classification"
  backbone: "resnet18"
  num_classes: 100
  pretrained: true

loss:
  name: "cross_entropy"
  label_smoothing: 0.1

optim:
  opt: "adamw"
  lr: 1e-3
  betas: [0.9, 0.999]
  eps: 1e-8
  weight_decay: 1e-4

scheduler:
  name: "cosine_annealing"
  T_max: 10
  eta_min: 0.001
